3rd: ciborium: Update submodule to resolve clippy errors
The update is for addressing the below clippy errors which are caused
by rust toolchain update.

```
$ ./scripts/clippy.sh
...
    Compiling lock_api v0.4.12
     Checking spin v0.5.2
error: usage of a legacy numeric constant
   --> third-party/ciborium/ciborium-ll/src/hdr.rs:122:23
    |
122 |             x if x <= core::u8::MAX as u64 => Minor::Next1([i as u8]),
    |                       ^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/inde
note: the lint level is defined here
...
```

Signed-off-by: Changho Choi <ch754.choi@samsung.com>