Disable panic module in model checking
This is required to avoid the following errors.
```
error: the `#[alloc_error_handler]` in islet_rmm conflicts with allocation error handler in: std

error[E0152]: duplicate lang item in crate `std` (which `kani` depends on): `panic_impl`.

error: aborting due to previous error

error: could not compile `fvp` (bin "fvp") due to 2 previous errors
error: Failed to execute cargo (exit status: 101). Found 2 compilation errors.
make: *** [Makefile:8: verify] Error 1
```