sdk: Use openssl instead of rsa to avoid a vulnerability
This commit is for resolving the following error in ci.
```
Run actions-rs/audit-check@v1
/home/runner/.cargo/bin/cargo generate-lockfile
    Updating crates.io index
Calling cargo-audit (JSON output)
Warning: 1 vulnerabilities found!
Warning: 1 warnings found!
Found 1 advisory(ies), 1 other
Warning: Unknown warning kind unsound found, please, file a bug
Error: Critical vulnerabilities were found, marking check as failed
```

The vulnerability (CVE-2023-49092) has been reported to be inside rsa crate.
```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 580 security advisories (from /home/changho/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (129 crate dependencies)
Crate:     rsa
Version:   0.9.5
Title:     Marvin Attack: potential key recovery through timing sidechannels
Date:      2023-11-22
ID:        RUSTSEC-2023-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
Solution:  No fixed upgrade is available!
Dependency tree:
rsa 0.9.5
└── islet_sdk 0.1.0

error: 1 vulnerability found!
```