ci: Exclude ciborium in cargo check
This commit is required to avoid the below issue in CI.

```
$ cargo check --workspace --exclude islet_sdk --exclude rsi_el0 --exclude cose --exclude cca_token
...
    Checking ciborium-io v0.2.2 (/home/changho/zpzigi754/islet/third-party/ciborium/ciborium-io)
error[E0463]: can't find crate for `std`
  |
  = note: the `aarch64-unknown-none-softfloat` target may not support the standard library
  = note: `std` is required by `ciborium_io` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
  --> third-party/ciborium/ciborium-io/src/lib.rs:57:9
   |
57 | impl<T: std::io::Read> Read for T {
   |         ^^^ can't find crate
   |
   = note: the `aarch64-unknown-none-softfloat` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`

error[E0463]: can't find crate for `std`
  --> third-party/ciborium/ciborium-io/src/lib.rs:58:18
   |
58 |     type Error = std::io::Error;
   |                  ^^^ can't find crate
   |
   = note: the `aarch64-unknown-none-softfloat` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

Signed-off-by: Changho Choi <ch754.choi@samsung.com>