Add neon in target-feature to resolve a dependency issue
This commit would resolve the below issue in CI, which was
caused by `half` crate's version update.

```
(in plat/fvp)
$ cargo build
...
error: register class `vreg` requires the `neon` target feature
   --> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/binary16/arch/aarch64.rs:171:9
    |
171 |         in(vreg) a,
    |         ^^^^^^^^^^

error: register class `vreg` requires the `neon` target feature
   --> /home/changho/.cargo/registry/src/index.crates.io-6f17d22bba15001f/half-2.3.1/src/binary16/arch/aarch64.rs:172:9
    |
172 |         in(vreg) b,
    |         ^^^^^^^^^^

error: could not compile `half` (lib) due to 32 previous errors
```

Signed-off-by: Changho Choi <ch754.choi@samsung.com>