rmi: Fix overflow in RMI_RTT_SET_RIPAS
- Bug Type: Overflow
- Cause: Overflow occurs when `top` is smaller than `GRANULE_SIZE`
- Solution: Return an error when an overflow is detected.
- Possible Flows:
  1) RMI_REC_ENTER is skipped, and RMI_RTT_SET_RIPAS is called with
     `top` smaller than `GRANULE_SIZE`.
  2) Even if RMI_REC_ENTER is called first, `top` is set to a value
     smaller than 'GRANULE_SIZE' by RSI_IPA_STATE_SET,
     followed by a call to RMI_RTT_SET_RIPAS

```sh
note: inside closure
   --> rmm/src/rmi/rtt.rs:649:36
    |
648 |     #[test]
    |     ------- in this procedural macro expansion
649 |     fn rmi_rtt_set_ripas_positive() {
    |                                    ^
    = note: this warning originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

thread 'rmi::rtt::test::rmi_rtt_set_ripas_positive' panicked at rmm/src/rmi/rtt.rs:138:32:
attempt to subtract with overflow
```

Signed-off-by: Sangwan Kwon <sangwan.kwon@samsung.com>