Update rustc to 1.88.0-nightly
This is for fixing ci issues encountered while executing ./scripts/deps/cross.sh.

```
 error: failed to compile `cross v0.2.5 (https://github.com/cross-rs/cross#49cd054d)`, intermediate artifacts can be found at `/tmp/cargo-installSPW8yI`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.85.0-nightly is not supported by the following package:
    home@0.5.12 requires rustc 1.88
  Either upgrade rustc or select compatible dependency versions with
  `cargo update <name>@<current-ver> --precise <compatible-ver>`
  where `<compatible-ver>` is the latest version supporting rustc 1.85.0-nightly
Error: Process completed with exit code 101.
```

Signed-off-by: Changho Choi <ch754.choi@samsung.com>