Remove extern keyword in panic handler
This is required to avoid the following error.
```
error[E0308]: `#[panic_handler]` function has wrong type
  --> rmm/src/panic.rs:15:1
   |
15 | pub extern "C" fn panic_handler(_info: &core::panic::PanicInfo<'_>) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected "Rust" fn, found "C" fn
   |
   = note: expected signature `for<'a, 'b> fn(&'a core::panic::PanicInfo<'b>) -> _`
              found signature `extern "C" for<'a, 'b> fn(&'a core::panic::PanicInfo<'b>) -> _`
```