ci: Fix the issue regarding not found
This commit fixes the below issue.

```
Run ./scripts/init_min.sh
...
0 upgraded, 65 newly installed, 0 to remove and 30 not upgraded.
Need to get 54.1 MB of archives.
After this operation, 220 MB of additional disk space will be used.
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev-i386_2.35-0ubuntu3.3_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-x32_2.35-0ubuntu3.3_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev-x32_2.35-0ubuntu3.3_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```