exception: handle access to ICC_x_EL1 registers from realms
Handle exceptions taken to RMM from a realm due to the access to
icc_x registers including ICC_DIR_EL1, ICC_SGI1R_EL1, ICC_SGI0R_EL1,
and ICC_PMR_EL1.
These make the realm exit and return to the host.

Signed-off-by: Bokdeuk Jeong <bd.jeong@samsung.com>